#include <cuda_runtime.h>
#include <math.h>

__global__ void tanh_kernel(const float* input, float* output, int N) {
    int idx = blockIdx.x * blockDim.x + threadIdx.x;
    if (idx < N) {
        float v = input[idx];
        //We could've used the expf function 
        //but the large |x|, expf(x) will overflow and the smaller expf(-x) will underflow.
        output[idx] = tanhf(v);
    }
}

extern "C" void solve(const float* input, float* output, int N) {
    int threads = 256;
    int blocks = (N + threads - 1) / threads;
    tanh_kernel<<<blocks, threads>>>(input, output, N);
    cudaDeviceSynchronize();
}

//PTX Code from LeetGPU
// //
// // Generated by NVIDIA NVVM Compiler
// //
// // Compiler Build ID: CL-35404655
// // Cuda compilation tools, release 12.8, V12.8.61
// // Based on NVVM 7.0.1
// //

// .version 8.7
// .target sm_75
// .address_size 64

// 	// .globl	tanh_kernel(float const*, float*, int)

// .visible .entry tanh_kernel(float const*, float*, int)(
// 	.param .u64 _Z11tanh_kernelPKfPfi_param_0,
// 	.param .u64 _Z11tanh_kernelPKfPfi_param_1,
// 	.param .u32 _Z11tanh_kernelPKfPfi_param_2
// )
// {
// 	.reg .pred 	%p<4>;
// 	.reg .f32 	%f<24>;
// 	.reg .b32 	%r<10>;
// 	.reg .b64 	%rd<8>;


// 	ld.param.u64 	%rd1, [_Z11tanh_kernelPKfPfi_param_0];
// 	ld.param.u64 	%rd2, [_Z11tanh_kernelPKfPfi_param_1];
// 	ld.param.u32 	%r2, [_Z11tanh_kernelPKfPfi_param_2];
// 	mov.u32 	%r3, %ctaid.x;
// 	mov.u32 	%r4, %ntid.x;
// 	mov.u32 	%r5, %tid.x;
// 	mad.lo.s32 	%r1, %r3, %r4, %r5;
// 	setp.ge.s32 	%p1, %r1, %r2;
// 	@%p1 bra 	$L__BB0_2;

// 	cvta.to.global.u64 	%rd3, %rd1;
// 	mul.wide.s32 	%rd4, %r1, 4;
// 	add.s64 	%rd5, %rd3, %rd4;
// 	ld.global.f32 	%f1, [%rd5];
// 	abs.f32 	%f2, %f1;
// 	mul.f32 	%f3, %f2, 0f4038AA3B;
// 	ex2.approx.ftz.f32 	%f4, %f3;
// 	add.f32 	%f5, %f4, 0f3F800000;
// 	mov.f32 	%f6, 0f3F800000;
// 	rcp.approx.ftz.f32 	%f7, %f5;
// 	mov.f32 	%f8, 0fC0000000;
// 	fma.rn.f32 	%f9, %f7, %f8, %f6;
// 	setp.ge.f32 	%p2, %f2, 0f41102CB4;
// 	selp.f32 	%f10, 0f3F800000, %f9, %p2;
// 	mov.b32 	%r6, %f10;
// 	mov.b32 	%r7, %f1;
// 	and.b32 	%r8, %r7, -2147483648;
// 	or.b32 	%r9, %r8, %r6;
// 	mov.b32 	%f11, %r9;
// 	mul.f32 	%f12, %f1, %f1;
// 	mov.f32 	%f13, 0fBD563CAE;
// 	mov.f32 	%f14, 0f3C80F082;
// 	fma.rn.f32 	%f15, %f14, %f12, %f13;
// 	mov.f32 	%f16, 0f3E085941;
// 	fma.rn.f32 	%f17, %f15, %f12, %f16;
// 	mov.f32 	%f18, 0fBEAAA9ED;
// 	fma.rn.f32 	%f19, %f17, %f12, %f18;
// 	mov.f32 	%f20, 0f00000000;
// 	fma.rn.f32 	%f21, %f19, %f12, %f20;
// 	fma.rn.f32 	%f22, %f21, %f1, %f1;
// 	setp.ge.f32 	%p3, %f2, 0f3F19999A;
// 	selp.f32 	%f23, %f11, %f22, %p3;
// 	cvta.to.global.u64 	%rd6, %rd2;
// 	add.s64 	%rd7, %rd6, %rd4;
// 	st.global.f32 	[%rd7], %f23;

// $L__BB0_2:
// 	ret;

// }
