#include <cuda_runtime.h>

__global__ void matrix_transpose_kernel(const float* A, float* B, int M, int N) {
    int idx = blockIdx.x * blockDim.x + threadIdx.x; //Column index j(0 to N -1)
    int idy = blockIdx.y * blockDim.y + threadIdx.y; //Row index i(0 to M-1)
    if (idy < M && idx < N) {
        B[idx * M + idy] = A[idy * N + idx];
    }
}

// //A more optimized version for tile dim 32
// #define TILE_DIM 32

// __global__ void matrix_transpose_kernel(const float* input, float* output, int M, int N) {
//     //Padding dimensions by +1 to avoid memory bank conflicts
//     __shared__ float tile[TILE_DIM][TILE_DIM + 1];

//     //Global reading coordinates
//     int in_x = blockIdx.x * TILE_DIM + threadIdx.x;
//     int in_y = blockIdx.y * TILE_DIM + threadIdx.y;

//     //Coalesced global memory read into shared memory
//     if (in_x < N && in_y < M) {
//         tile[threadIdx.y][threadIdx.x] = input[in_y * N + in_x];
//     }

//     __syncthreads();


//     //Re-map thread block coordinates for output writing
//     int out_x = blockIdx.y * TILE_DIM + threadIdx.x;
//     int out_y = blockIdx.x * TILE_DIM + threadIdx.y;


//     //Coalesced global memory write into shared memory
//     if (out_x < M && out_y < N) {
//         output[out_y * M + out_x] = tile[threadIdx.x][threadIdx.y];
//     }
// }

extern "C" void solve(const float* A, float* B, int M, int N) {
    dim3 threads(16, 16);
    dim3 blocks((N + 15) / 16, (M + 15) / 16);
    matrix_transpose_kernel<<<blocks, threads>>>(A, B, M, N);
    cudaDeviceSynchronize();
}


//PTX from leet GPU

//Optimized version:
// //
// // Generated by NVIDIA NVVM Compiler
// //
// // Compiler Build ID: CL-35404655
// // Cuda compilation tools, release 12.8, V12.8.61
// // Based on NVVM 7.0.1
// //

// .version 8.7
// .target sm_75
// .address_size 64

// 	// .globl	matrix_transpose_kernel(float const*, float*, int, int)
// // matrix_transpose_kernel(float const*, float*, int, int)::tile has been demoted

// .visible .entry matrix_transpose_kernel(float const*, float*, int, int)(
// 	.param .u64 _Z23matrix_transpose_kernelPKfPfii_param_0,
// 	.param .u64 _Z23matrix_transpose_kernelPKfPfii_param_1,
// 	.param .u32 _Z23matrix_transpose_kernelPKfPfii_param_2,
// 	.param .u32 _Z23matrix_transpose_kernelPKfPfii_param_3
// )
// {
// 	.reg .pred 	%p<7>;
// 	.reg .f32 	%f<3>;
// 	.reg .b32 	%r<23>;
// 	.reg .b64 	%rd<9>;
// 	// demoted variable
// 	.shared .align 4 .b8 matrix_transpose_kernel(float const*, float*, int, int)::tile[4224];

// 	ld.param.u64 	%rd1, [_Z23matrix_transpose_kernelPKfPfii_param_0];
// 	ld.param.u64 	%rd2, [_Z23matrix_transpose_kernelPKfPfii_param_1];
// 	ld.param.u32 	%r9, [_Z23matrix_transpose_kernelPKfPfii_param_2];
// 	ld.param.u32 	%r10, [_Z23matrix_transpose_kernelPKfPfii_param_3];
// 	mov.u32 	%r11, %ctaid.x;
// 	shl.b32 	%r1, %r11, 5;
// 	mov.u32 	%r2, %tid.x;
// 	add.s32 	%r3, %r1, %r2;
// 	mov.u32 	%r12, %ctaid.y;
// 	shl.b32 	%r4, %r12, 5;
// 	mov.u32 	%r5, %tid.y;
// 	add.s32 	%r6, %r4, %r5;
// 	setp.ge.s32 	%p1, %r3, %r10;
// 	setp.ge.s32 	%p2, %r6, %r9;
// 	or.pred 	%p3, %p2, %p1;
// 	@%p3 bra 	$L__BB0_2;

// 	cvta.to.global.u64 	%rd3, %rd1;
// 	mad.lo.s32 	%r13, %r6, %r10, %r3;
// 	mul.wide.s32 	%rd4, %r13, 4;
// 	add.s64 	%rd5, %rd3, %rd4;
// 	ld.global.f32 	%f1, [%rd5];
// 	mov.u32 	%r14, matrix_transpose_kernel(float const*, float*, int, int)::tile;
// 	mad.lo.s32 	%r15, %r5, 132, %r14;
// 	shl.b32 	%r16, %r2, 2;
// 	add.s32 	%r17, %r15, %r16;
// 	st.shared.f32 	[%r17], %f1;

// $L__BB0_2:
// 	bar.sync 	0;
// 	add.s32 	%r7, %r4, %r2;
// 	setp.ge.s32 	%p4, %r7, %r9;
// 	add.s32 	%r8, %r1, %r5;
// 	setp.ge.s32 	%p5, %r8, %r10;
// 	or.pred 	%p6, %p4, %p5;
// 	@%p6 bra 	$L__BB0_4;

// 	mov.u32 	%r18, matrix_transpose_kernel(float const*, float*, int, int)::tile;
// 	mad.lo.s32 	%r19, %r2, 132, %r18;
// 	shl.b32 	%r20, %r5, 2;
// 	add.s32 	%r21, %r19, %r20;
// 	ld.shared.f32 	%f2, [%r21];
// 	mad.lo.s32 	%r22, %r8, %r9, %r7;
// 	cvta.to.global.u64 	%rd6, %rd2;
// 	mul.wide.s32 	%rd7, %r22, 4;
// 	add.s64 	%rd8, %rd6, %rd7;
// 	st.global.f32 	[%rd8], %f2;

// $L__BB0_4:
// 	ret;

// }

//Normal Version:
// //
// // Generated by NVIDIA NVVM Compiler
// //
// // Compiler Build ID: CL-35404655
// // Cuda compilation tools, release 12.8, V12.8.61
// // Based on NVVM 7.0.1
// //

// .version 8.7
// .target sm_75
// .address_size 64

// 	// .globl	matrix_transpose_kernel(float const*, float*, int, int)

// .visible .entry matrix_transpose_kernel(float const*, float*, int, int)(
// 	.param .u64 _Z23matrix_transpose_kernelPKfPfii_param_0,
// 	.param .u64 _Z23matrix_transpose_kernelPKfPfii_param_1,
// 	.param .u32 _Z23matrix_transpose_kernelPKfPfii_param_2,
// 	.param .u32 _Z23matrix_transpose_kernelPKfPfii_param_3
// )
// {
// 	.reg .pred 	%p<4>;
// 	.reg .f32 	%f<2>;
// 	.reg .b32 	%r<13>;
// 	.reg .b64 	%rd<9>;


// 	ld.param.u64 	%rd1, [_Z23matrix_transpose_kernelPKfPfii_param_0];
// 	ld.param.u64 	%rd2, [_Z23matrix_transpose_kernelPKfPfii_param_1];
// 	ld.param.u32 	%r3, [_Z23matrix_transpose_kernelPKfPfii_param_2];
// 	ld.param.u32 	%r4, [_Z23matrix_transpose_kernelPKfPfii_param_3];
// 	mov.u32 	%r5, %ctaid.x;
// 	mov.u32 	%r6, %ntid.x;
// 	mov.u32 	%r7, %tid.x;
// 	mad.lo.s32 	%r1, %r5, %r6, %r7;
// 	mov.u32 	%r8, %ntid.y;
// 	mov.u32 	%r9, %ctaid.y;
// 	mov.u32 	%r10, %tid.y;
// 	mad.lo.s32 	%r2, %r9, %r8, %r10;
// 	setp.ge.s32 	%p1, %r1, %r4;
// 	setp.ge.s32 	%p2, %r2, %r3;
// 	or.pred 	%p3, %p2, %p1;
// 	@%p3 bra 	$L__BB0_2;

// 	cvta.to.global.u64 	%rd3, %rd1;
// 	mad.lo.s32 	%r11, %r2, %r4, %r1;
// 	mul.wide.s32 	%rd4, %r11, 4;
// 	add.s64 	%rd5, %rd3, %rd4;
// 	ld.global.f32 	%f1, [%rd5];
// 	mad.lo.s32 	%r12, %r1, %r3, %r2;
// 	cvta.to.global.u64 	%rd6, %rd2;
// 	mul.wide.s32 	%rd7, %r12, 4;
// 	add.s64 	%rd8, %rd6, %rd7;
// 	st.global.f32 	[%rd8], %f1;

// $L__BB0_2:
// 	ret;

// }