#include <cuda_runtime.h>
#include <math.h>

__global__ void gelu_kernel(const float* input, float* output, int N) {
    int idx = blockIdx.x * blockDim.x + threadIdx.x;
    if (idx < N) {
        float x = input[idx];
        output[idx] = 0.5f * x * (1.0f + erff(x / sqrt(2.0f)));
    }
}

extern "C" void solve(const float* input, float* output, int N) {
    int threads = 256;
    dim3 blocks((N + 255) / 256);
    gelu_kernel<<<blocks, threads>>>(input, output, N);
    cudaDeviceSynchronize();
}

//PTX Code from native nvcc
// //
// // Generated by NVIDIA NVVM Compiler
// //
// // Compiler Build ID: CL-37061995
// //CUDA compilation tools, release 13.1, V13.1.115
// // Based on NVVM 7.0.1
// //

// .version 9.1
// .target sm_75
// .address_size 64

// 	// .globl	_Z11gelu_kernelPKfPfi

// .visible .entry _Z11gelu_kernelPKfPfi(
// 	.param .u64 _Z11gelu_kernelPKfPfi_param_0,
// 	.param .u64 _Z11gelu_kernelPKfPfi_param_1,
// 	.param .u32 _Z11gelu_kernelPKfPfi_param_2
// )
// {
// 	.reg .pred 	%p<4>;
// 	.reg .f32 	%f<31>;
// 	.reg .b32 	%r<6>;
// 	.reg .b64 	%rd<10>;


// 	ld.param.u64 	%rd2, [_Z11gelu_kernelPKfPfi_param_0];
// 	ld.param.u64 	%rd3, [_Z11gelu_kernelPKfPfi_param_1];
// 	ld.param.u32 	%r2, [_Z11gelu_kernelPKfPfi_param_2];
// 	mov.u32 	%r3, %ctaid.x;
// 	mov.u32 	%r4, %ntid.x;
// 	mov.u32 	%r5, %tid.x;
// 	mad.lo.s32 	%r1, %r3, %r4, %r5;
// 	setp.ge.s32 	%p1, %r1, %r2;
// 	@%p1 bra 	$L__BB0_4;

// 	cvta.to.global.u64 	%rd4, %rd2;
// 	cvt.s64.s32 	%rd1, %r1;
// 	mul.wide.s32 	%rd5, %r1, 4;
// 	add.s64 	%rd6, %rd4, %rd5;
// 	ld.global.f32 	%f1, [%rd6];
// 	div.rn.f32 	%f2, %f1, 0f3FB504F3;
// 	abs.f32 	%f6, %f2;
// 	setp.ltu.f32 	%p2, %f6, 0f3F8060FE;
// 	setp.ge.f32 	%p3, %f6, 0f3F8060FE;
// 	mul.f32 	%f7, %f2, %f2;
// 	selp.f32 	%f8, %f6, %f7, %p3;
// 	selp.f32 	%f9, 0f38EB4C3A, 0f38B1E96A, %p3;
// 	selp.f32 	%f10, 0fBAAE005B, 0fBA574D20, %p3;
// 	fma.rn.f32 	%f11, %f9, %f8, %f10;
// 	selp.f32 	%f12, 0f3C09919F, 0f3BAAD5EA, %p3;
// 	fma.rn.f32 	%f13, %f11, %f8, %f12;
// 	selp.f32 	%f14, 0fBD24D99A, 0fBCDC1BE7, %p3;
// 	fma.rn.f32 	%f15, %f13, %f8, %f14;
// 	selp.f32 	%f16, 0f3E235519, 0f3DE718AF, %p3;
// 	fma.rn.f32 	%f17, %f15, %f8, %f16;
// 	selp.f32 	%f18, 0f3F69B4F9, 0fBEC093AC, %p3;
// 	fma.rn.f32 	%f19, %f17, %f8, %f18;
// 	selp.f32 	%f20, 0f3F210A14, 0f3E0375D3, %p3;
// 	fma.rn.f32 	%f21, %f19, %f8, %f20;
// 	neg.f32 	%f22, %f6;
// 	selp.f32 	%f23, %f22, %f2, %p3;
// 	fma.rn.f32 	%f30, %f21, %f23, %f23;
// 	@%p2 bra 	$L__BB0_3;

// 	ex2.approx.ftz.f32 	%f24, %f30;
// 	mov.f32 	%f25, 0f3F800000;
// 	sub.f32 	%f26, %f25, %f24;
// 	copysign.f32 	%f30, %f2, %f26;

// $L__BB0_3:
// 	add.f32 	%f27, %f30, 0f3F800000;
// 	mul.f32 	%f28, %f1, 0f3F000000;
// 	mul.f32 	%f29, %f28, %f27;
// 	cvta.to.global.u64 	%rd7, %rd3;
// 	shl.b64 	%rd8, %rd1, 2;
// 	add.s64 	%rd9, %rd7, %rd8;
// 	st.global.f32 	[%rd9], %f29;

// $L__BB0_4:
// 	ret;

// }


