#include <cuda_runtime.h>
#include <math.h>

__global__ void sigmoid_kernel(const float* input, float* output, int N) {
    int idx  = blockIdx.x * blockDim.x + threadIdx.x;
    if (idx < N){
        float v = input[idx];
        output[idx] = (output > 0) ? 1.0f / (1.0f + __expf(-v)) : __expf(v / (1.0f + __expf(v)));
        
    }
    
}

extern "C" void solve(const float* input, float* output, int N) {
    int threads = 256;
    int blocks = (N + threads - 1) / threads;
    sigmoid_kernel<<<blocks, threads>>>(input, output, N);
    cudaDeviceSynchronize();
}

//PTX Code from LeetGPU
//
// Generated by NVIDIA NVVM Compiler
//
// Compiler Build ID: CL-35404655
// Cuda compilation tools, release 12.8, V12.8.61
// Based on NVVM 7.0.1
//

// .version 8.7
// .target sm_75
// .address_size 64

// 	// .globl	sigmoid_kernel(float const*, float*, int)

// .visible .entry sigmoid_kernel(float const*, float*, int)(
// 	.param .u64 _Z14sigmoid_kernelPKfPfi_param_0,
// 	.param .u64 _Z14sigmoid_kernelPKfPfi_param_1,
// 	.param .u32 _Z14sigmoid_kernelPKfPfi_param_2
// )
// {
// 	.reg .pred 	%p<3>;
// 	.reg .f32 	%f<27>;
// 	.reg .b32 	%r<8>;
// 	.reg .b64 	%rd<10>;


// 	ld.param.u64 	%rd2, [_Z14sigmoid_kernelPKfPfi_param_0];
// 	ld.param.u64 	%rd3, [_Z14sigmoid_kernelPKfPfi_param_1];
// 	ld.param.u32 	%r2, [_Z14sigmoid_kernelPKfPfi_param_2];
// 	mov.u32 	%r3, %ntid.x;
// 	mov.u32 	%r4, %ctaid.x;
// 	mov.u32 	%r5, %tid.x;
// 	mad.lo.s32 	%r1, %r4, %r3, %r5;
// 	setp.ge.s32 	%p1, %r1, %r2;
// 	@%p1 bra 	$L__BB0_5;

// 	cvta.to.global.u64 	%rd4, %rd2;
// 	cvt.s64.s32 	%rd1, %r1;
// 	mul.wide.s32 	%rd5, %r1, 4;
// 	add.s64 	%rd6, %rd4, %rd5;
// 	ld.global.f32 	%f1, [%rd6];
// 	setp.eq.s64 	%p2, %rd3, 0;
// 	@%p2 bra 	$L__BB0_3;

// 	mul.f32 	%f5, %f1, 0fBFB8AA3B;
// 	ex2.approx.f32 	%f6, %f5;
// 	add.f32 	%f7, %f6, 0f3F800000;
// 	rcp.rn.f32 	%f26, %f7;
// 	bra.uni 	$L__BB0_4;

// $L__BB0_3:
// 	mov.f32 	%f8, 0f3F000000;
// 	mov.f32 	%f9, 0f3BBB989D;
// 	fma.rn.f32 	%f10, %f1, %f9, %f8;
// 	cvt.sat.f32.f32 	%f11, %f10;
// 	mov.f32 	%f12, 0f4B400001;
// 	mov.f32 	%f13, 0f437C0000;
// 	fma.rm.f32 	%f14, %f11, %f13, %f12;
// 	add.f32 	%f15, %f14, 0fCB40007F;
// 	neg.f32 	%f16, %f15;
// 	mov.f32 	%f17, 0f3FB8AA3B;
// 	fma.rn.f32 	%f18, %f1, %f17, %f16;
// 	mov.f32 	%f19, 0f32A57060;
// 	fma.rn.f32 	%f20, %f1, %f19, %f18;
// 	mov.b32 	%r6, %f14;
// 	shl.b32 	%r7, %r6, 23;
// 	mov.b32 	%f21, %r7;
// 	ex2.approx.ftz.f32 	%f22, %f20;
// 	fma.rn.f32 	%f23, %f22, %f21, 0f3F800000;
// 	div.rn.f32 	%f24, %f1, %f23;
// 	mul.f32 	%f25, %f24, 0f3FB8AA3B;
// 	ex2.approx.f32 	%f26, %f25;

// $L__BB0_4:
// 	cvta.to.global.u64 	%rd7, %rd3;
// 	shl.b64 	%rd8, %rd1, 2;
// 	add.s64 	%rd9, %rd7, %rd8;
// 	st.global.f32 	[%rd9], %f26;

// $L__BB0_5:
// 	ret;

// }