#include <cuda_runtime.h>

__global__ void matrix_add_kernel(const float* A, const float* B, float* C, int M, int N) {
    //Shortest one yet
    int tid = (blockIdx.y * gridDim.x + blockIdx.x) * (blockDim.x * blockDim.y) + (threadIdx.y * blockDim.x + threadIdx.x);
    int total_elements = M * N;

    if (tid < total_elements) {
        C[tid] = A[tid] + B[tid];
    }
}

extern "C" void solve(const float* A, const float* B, float* C, int M, int N) {
    dim3 threads(16, 16);
    dim3 blocks((N + 15) / 16, (M + 15) / 16);
    matrix_add_kernel<<<blocks, threads>>>(A, B, C, M, N);
    cudaDeviceSynchronize();
}


//PTX from leetGPU
//
// Generated by NVIDIA NVVM Compiler
//
// Compiler Build ID: CL-35404655
// Cuda compilation tools, release 12.8, V12.8.61
// Based on NVVM 7.0.1
//

// .version 8.7
// .target sm_75
// .address_size 64

// 	// .globl	matrix_add_kernel(float const*, float const*, float*, int, int)

// .visible .entry matrix_add_kernel(float const*, float const*, float*, int, int)(
// 	.param .u64 _Z17matrix_add_kernelPKfS0_Pfii_param_0,
// 	.param .u64 _Z17matrix_add_kernelPKfS0_Pfii_param_1,
// 	.param .u64 _Z17matrix_add_kernelPKfS0_Pfii_param_2,
// 	.param .u32 _Z17matrix_add_kernelPKfS0_Pfii_param_3,
// 	.param .u32 _Z17matrix_add_kernelPKfS0_Pfii_param_4
// )
// {
// 	.reg .pred 	%p<2>;
// 	.reg .f32 	%f<4>;
// 	.reg .b32 	%r<14>;
// 	.reg .b64 	%rd<11>;


// 	ld.param.u64 	%rd1, [_Z17matrix_add_kernelPKfS0_Pfii_param_0];
// 	ld.param.u64 	%rd2, [_Z17matrix_add_kernelPKfS0_Pfii_param_1];
// 	ld.param.u64 	%rd3, [_Z17matrix_add_kernelPKfS0_Pfii_param_2];
// 	ld.param.u32 	%r2, [_Z17matrix_add_kernelPKfS0_Pfii_param_3];
// 	ld.param.u32 	%r3, [_Z17matrix_add_kernelPKfS0_Pfii_param_4];
// 	mov.u32 	%r4, %ctaid.y;
// 	mov.u32 	%r5, %nctaid.x;
// 	mov.u32 	%r6, %ctaid.x;
// 	mad.lo.s32 	%r7, %r4, %r5, %r6;
// 	mov.u32 	%r8, %ntid.y;
// 	mov.u32 	%r9, %tid.y;
// 	mad.lo.s32 	%r10, %r7, %r8, %r9;
// 	mov.u32 	%r11, %ntid.x;
// 	mov.u32 	%r12, %tid.x;
// 	mad.lo.s32 	%r1, %r10, %r11, %r12;
// 	mul.lo.s32 	%r13, %r3, %r2;
// 	setp.ge.s32 	%p1, %r1, %r13;
// 	@%p1 bra 	$L__BB0_2;

// 	cvta.to.global.u64 	%rd4, %rd1;
// 	mul.wide.s32 	%rd5, %r1, 4;
// 	add.s64 	%rd6, %rd4, %rd5;
// 	cvta.to.global.u64 	%rd7, %rd2;
// 	add.s64 	%rd8, %rd7, %rd5;
// 	ld.global.f32 	%f1, [%rd8];
// 	ld.global.f32 	%f2, [%rd6];
// 	add.f32 	%f3, %f2, %f1;
// 	cvta.to.global.u64 	%rd9, %rd3;
// 	add.s64 	%rd10, %rd9, %rd5;
// 	st.global.f32 	[%rd10], %f3;

// $L__BB0_2:
// 	ret;

// }