#include <cuda_runtime.h>

__global__ void softmax_kernel(const float* input, float* output, int N) {
    if (threadIdx.x == 0 && blockIdx.x == 0) {
        float max_val = -INFINITY;
        for(int i = 0; i < N; i++) max_val = fmaxf(max_val, input[i]);

        float sum = 0.0f;
        for (int i = 0; i < N; i++) sum += expf(input[i] - max_val);

        for (int i = 0; i < N; i++) output[i] = expf(input[i] - max_val) / sum;
    }
}

extern "C" void solve(const float* input, float* output, int N) {
    int threads = 256;
    int blocks = (N + threads - 1) / threads;
    softmax_kernel<<<blocks, threads>>>(input, output, N);
    cudaDeviceSynchronize();
}

//PTX from LeetGPU
// //
// // Generated by NVIDIA NVVM Compiler
// //
// // Compiler Build ID: CL-35404655
// // Cuda compilation tools, release 12.8, V12.8.61
// // Based on NVVM 7.0.1
// //

// .version 8.7
// .target sm_75
// .address_size 64

// 	// .globl	softmax_kernel(float const*, float*, int)

// .visible .entry softmax_kernel(float const*, float*, int)(
// 	.param .u64 _Z14softmax_kernelPKfPfi_param_0,
// 	.param .u64 _Z14softmax_kernelPKfPfi_param_1,
// 	.param .u32 _Z14softmax_kernelPKfPfi_param_2
// )
// {
// 	.reg .pred 	%p<17>;
// 	.reg .f32 	%f<188>;
// 	.reg .b32 	%r<73>;
// 	.reg .b64 	%rd<36>;


// 	ld.param.u64 	%rd23, [_Z14softmax_kernelPKfPfi_param_0];
// 	ld.param.u64 	%rd24, [_Z14softmax_kernelPKfPfi_param_1];
// 	ld.param.u32 	%r28, [_Z14softmax_kernelPKfPfi_param_2];
// 	cvta.to.global.u64 	%rd1, %rd24;
// 	cvta.to.global.u64 	%rd2, %rd23;
// 	mov.u32 	%r29, %ctaid.x;
// 	mov.u32 	%r30, %tid.x;
// 	or.b32 	%r31, %r30, %r29;
// 	setp.ne.s32 	%p1, %r31, 0;
// 	@%p1 bra 	$L__BB0_22;
// 	bra.uni 	$L__BB0_1;

// $L__BB0_22:
// 	ret;

// $L__BB0_1:
// 	setp.lt.s32 	%p2, %r28, 1;
// 	mov.f32 	%f182, 0fFF800000;
// 	@%p2 bra 	$L__BB0_8;

// 	add.s32 	%r33, %r28, -1;
// 	and.b32 	%r64, %r28, 3;
// 	setp.lt.u32 	%p3, %r33, 3;
// 	mov.f32 	%f182, 0fFF800000;
// 	mov.u32 	%r63, 0;
// 	@%p3 bra 	$L__BB0_5;

// 	sub.s32 	%r62, %r28, %r64;
// 	mov.f32 	%f182, 0fFF800000;
// 	mov.u32 	%r63, 0;
// 	mov.u64 	%rd28, %rd2;

// $L__BB0_4:
// 	ld.global.f32 	%f19, [%rd28];
// 	max.f32 	%f20, %f182, %f19;
// 	ld.global.f32 	%f21, [%rd28+4];
// 	max.f32 	%f22, %f20, %f21;
// 	ld.global.f32 	%f23, [%rd28+8];
// 	max.f32 	%f24, %f22, %f23;
// 	ld.global.f32 	%f25, [%rd28+12];
// 	max.f32 	%f182, %f24, %f25;
// 	add.s32 	%r63, %r63, 4;
// 	add.s64 	%rd28, %rd28, 16;
// 	add.s32 	%r62, %r62, -4;
// 	setp.ne.s32 	%p4, %r62, 0;
// 	@%p4 bra 	$L__BB0_4;

// $L__BB0_5:
// 	setp.eq.s32 	%p5, %r64, 0;
// 	@%p5 bra 	$L__BB0_8;

// 	mul.wide.s32 	%rd25, %r63, 4;
// 	add.s64 	%rd29, %rd2, %rd25;

// $L__BB0_7:
// 	.pragma "nounroll";
// 	ld.global.f32 	%f26, [%rd29];
// 	max.f32 	%f182, %f182, %f26;
// 	add.s64 	%rd29, %rd29, 4;
// 	add.s32 	%r64, %r64, -1;
// 	setp.ne.s32 	%p6, %r64, 0;
// 	@%p6 bra 	$L__BB0_7;

// $L__BB0_8:
// 	mov.f32 	%f187, 0f00000000;
// 	@%p2 bra 	$L__BB0_15;

// 	add.s32 	%r36, %r28, -1;
// 	and.b32 	%r68, %r28, 3;
// 	setp.lt.u32 	%p8, %r36, 3;
// 	mov.f32 	%f187, 0f00000000;
// 	mov.u32 	%r67, 0;
// 	@%p8 bra 	$L__BB0_12;

// 	sub.s32 	%r66, %r28, %r68;
// 	mov.f32 	%f187, 0f00000000;
// 	mov.u32 	%r67, 0;
// 	mov.u64 	%rd30, %rd2;

// $L__BB0_11:
// 	ld.global.f32 	%f31, [%rd30];
// 	sub.f32 	%f32, %f31, %f182;
// 	mov.f32 	%f33, 0f3F000000;
// 	mov.f32 	%f34, 0f3BBB989D;
// 	fma.rn.f32 	%f35, %f32, %f34, %f33;
// 	cvt.sat.f32.f32 	%f36, %f35;
// 	mov.f32 	%f37, 0f4B400001;
// 	mov.f32 	%f38, 0f437C0000;
// 	fma.rm.f32 	%f39, %f36, %f38, %f37;
// 	add.f32 	%f40, %f39, 0fCB40007F;
// 	neg.f32 	%f41, %f40;
// 	mov.f32 	%f42, 0f3FB8AA3B;
// 	fma.rn.f32 	%f43, %f32, %f42, %f41;
// 	mov.f32 	%f44, 0f32A57060;
// 	fma.rn.f32 	%f45, %f32, %f44, %f43;
// 	mov.b32 	%r38, %f39;
// 	shl.b32 	%r39, %r38, 23;
// 	mov.b32 	%f46, %r39;
// 	ex2.approx.ftz.f32 	%f47, %f45;
// 	fma.rn.f32 	%f48, %f47, %f46, %f187;
// 	ld.global.f32 	%f49, [%rd30+4];
// 	sub.f32 	%f50, %f49, %f182;
// 	fma.rn.f32 	%f51, %f50, %f34, %f33;
// 	cvt.sat.f32.f32 	%f52, %f51;
// 	fma.rm.f32 	%f53, %f52, %f38, %f37;
// 	add.f32 	%f54, %f53, 0fCB40007F;
// 	neg.f32 	%f55, %f54;
// 	fma.rn.f32 	%f56, %f50, %f42, %f55;
// 	fma.rn.f32 	%f57, %f50, %f44, %f56;
// 	mov.b32 	%r40, %f53;
// 	shl.b32 	%r41, %r40, 23;
// 	mov.b32 	%f58, %r41;
// 	ex2.approx.ftz.f32 	%f59, %f57;
// 	fma.rn.f32 	%f60, %f59, %f58, %f48;
// 	ld.global.f32 	%f61, [%rd30+8];
// 	sub.f32 	%f62, %f61, %f182;
// 	fma.rn.f32 	%f63, %f62, %f34, %f33;
// 	cvt.sat.f32.f32 	%f64, %f63;
// 	fma.rm.f32 	%f65, %f64, %f38, %f37;
// 	add.f32 	%f66, %f65, 0fCB40007F;
// 	neg.f32 	%f67, %f66;
// 	fma.rn.f32 	%f68, %f62, %f42, %f67;
// 	fma.rn.f32 	%f69, %f62, %f44, %f68;
// 	mov.b32 	%r42, %f65;
// 	shl.b32 	%r43, %r42, 23;
// 	mov.b32 	%f70, %r43;
// 	ex2.approx.ftz.f32 	%f71, %f69;
// 	fma.rn.f32 	%f72, %f71, %f70, %f60;
// 	ld.global.f32 	%f73, [%rd30+12];
// 	sub.f32 	%f74, %f73, %f182;
// 	fma.rn.f32 	%f75, %f74, %f34, %f33;
// 	cvt.sat.f32.f32 	%f76, %f75;
// 	fma.rm.f32 	%f77, %f76, %f38, %f37;
// 	add.f32 	%f78, %f77, 0fCB40007F;
// 	neg.f32 	%f79, %f78;
// 	fma.rn.f32 	%f80, %f74, %f42, %f79;
// 	fma.rn.f32 	%f81, %f74, %f44, %f80;
// 	mov.b32 	%r44, %f77;
// 	shl.b32 	%r45, %r44, 23;
// 	mov.b32 	%f82, %r45;
// 	ex2.approx.ftz.f32 	%f83, %f81;
// 	fma.rn.f32 	%f187, %f83, %f82, %f72;
// 	add.s32 	%r67, %r67, 4;
// 	add.s64 	%rd30, %rd30, 16;
// 	add.s32 	%r66, %r66, -4;
// 	setp.ne.s32 	%p9, %r66, 0;
// 	@%p9 bra 	$L__BB0_11;

// $L__BB0_12:
// 	setp.eq.s32 	%p10, %r68, 0;
// 	@%p10 bra 	$L__BB0_15;

// 	mul.wide.s32 	%rd26, %r67, 4;
// 	add.s64 	%rd31, %rd2, %rd26;

// $L__BB0_14:
// 	.pragma "nounroll";
// 	ld.global.f32 	%f84, [%rd31];
// 	sub.f32 	%f85, %f84, %f182;
// 	mov.f32 	%f86, 0f3F000000;
// 	mov.f32 	%f87, 0f3BBB989D;
// 	fma.rn.f32 	%f88, %f85, %f87, %f86;
// 	cvt.sat.f32.f32 	%f89, %f88;
// 	mov.f32 	%f90, 0f4B400001;
// 	mov.f32 	%f91, 0f437C0000;
// 	fma.rm.f32 	%f92, %f89, %f91, %f90;
// 	add.f32 	%f93, %f92, 0fCB40007F;
// 	neg.f32 	%f94, %f93;
// 	mov.f32 	%f95, 0f3FB8AA3B;
// 	fma.rn.f32 	%f96, %f85, %f95, %f94;
// 	mov.f32 	%f97, 0f32A57060;
// 	fma.rn.f32 	%f98, %f85, %f97, %f96;
// 	mov.b32 	%r46, %f92;
// 	shl.b32 	%r47, %r46, 23;
// 	mov.b32 	%f99, %r47;
// 	ex2.approx.ftz.f32 	%f100, %f98;
// 	fma.rn.f32 	%f187, %f100, %f99, %f187;
// 	add.s64 	%rd31, %rd31, 4;
// 	add.s32 	%r68, %r68, -1;
// 	setp.ne.s32 	%p11, %r68, 0;
// 	@%p11 bra 	$L__BB0_14;

// $L__BB0_15:
// 	@%p2 bra 	$L__BB0_22;

// 	add.s32 	%r49, %r28, -1;
// 	and.b32 	%r72, %r28, 3;
// 	setp.lt.u32 	%p13, %r49, 3;
// 	mov.u32 	%r71, 0;
// 	@%p13 bra 	$L__BB0_19;

// 	sub.s32 	%r70, %r28, %r72;
// 	mov.u32 	%r71, 0;
// 	mov.u64 	%rd32, %rd1;
// 	mov.u64 	%rd33, %rd2;

// $L__BB0_18:
// 	ld.global.f32 	%f101, [%rd33];
// 	sub.f32 	%f102, %f101, %f182;
// 	mov.f32 	%f103, 0f3F000000;
// 	mov.f32 	%f104, 0f3BBB989D;
// 	fma.rn.f32 	%f105, %f102, %f104, %f103;
// 	cvt.sat.f32.f32 	%f106, %f105;
// 	mov.f32 	%f107, 0f4B400001;
// 	mov.f32 	%f108, 0f437C0000;
// 	fma.rm.f32 	%f109, %f106, %f108, %f107;
// 	add.f32 	%f110, %f109, 0fCB40007F;
// 	neg.f32 	%f111, %f110;
// 	mov.f32 	%f112, 0f3FB8AA3B;
// 	fma.rn.f32 	%f113, %f102, %f112, %f111;
// 	mov.f32 	%f114, 0f32A57060;
// 	fma.rn.f32 	%f115, %f102, %f114, %f113;
// 	mov.b32 	%r51, %f109;
// 	shl.b32 	%r52, %r51, 23;
// 	mov.b32 	%f116, %r52;
// 	ex2.approx.ftz.f32 	%f117, %f115;
// 	mul.f32 	%f118, %f117, %f116;
// 	div.rn.f32 	%f119, %f118, %f187;
// 	st.global.f32 	[%rd32], %f119;
// 	ld.global.f32 	%f120, [%rd33+4];
// 	sub.f32 	%f121, %f120, %f182;
// 	fma.rn.f32 	%f122, %f121, %f104, %f103;
// 	cvt.sat.f32.f32 	%f123, %f122;
// 	fma.rm.f32 	%f124, %f123, %f108, %f107;
// 	add.f32 	%f125, %f124, 0fCB40007F;
// 	neg.f32 	%f126, %f125;
// 	fma.rn.f32 	%f127, %f121, %f112, %f126;
// 	fma.rn.f32 	%f128, %f121, %f114, %f127;
// 	mov.b32 	%r53, %f124;
// 	shl.b32 	%r54, %r53, 23;
// 	mov.b32 	%f129, %r54;
// 	ex2.approx.ftz.f32 	%f130, %f128;
// 	mul.f32 	%f131, %f130, %f129;
// 	div.rn.f32 	%f132, %f131, %f187;
// 	st.global.f32 	[%rd32+4], %f132;
// 	ld.global.f32 	%f133, [%rd33+8];
// 	sub.f32 	%f134, %f133, %f182;
// 	fma.rn.f32 	%f135, %f134, %f104, %f103;
// 	cvt.sat.f32.f32 	%f136, %f135;
// 	fma.rm.f32 	%f137, %f136, %f108, %f107;
// 	add.f32 	%f138, %f137, 0fCB40007F;
// 	neg.f32 	%f139, %f138;
// 	fma.rn.f32 	%f140, %f134, %f112, %f139;
// 	fma.rn.f32 	%f141, %f134, %f114, %f140;
// 	mov.b32 	%r55, %f137;
// 	shl.b32 	%r56, %r55, 23;
// 	mov.b32 	%f142, %r56;
// 	ex2.approx.ftz.f32 	%f143, %f141;
// 	mul.f32 	%f144, %f143, %f142;
// 	div.rn.f32 	%f145, %f144, %f187;
// 	st.global.f32 	[%rd32+8], %f145;
// 	ld.global.f32 	%f146, [%rd33+12];
// 	sub.f32 	%f147, %f146, %f182;
// 	fma.rn.f32 	%f148, %f147, %f104, %f103;
// 	cvt.sat.f32.f32 	%f149, %f148;
// 	fma.rm.f32 	%f150, %f149, %f108, %f107;
// 	add.f32 	%f151, %f150, 0fCB40007F;
// 	neg.f32 	%f152, %f151;
// 	fma.rn.f32 	%f153, %f147, %f112, %f152;
// 	fma.rn.f32 	%f154, %f147, %f114, %f153;
// 	mov.b32 	%r57, %f150;
// 	shl.b32 	%r58, %r57, 23;
// 	mov.b32 	%f155, %r58;
// 	ex2.approx.ftz.f32 	%f156, %f154;
// 	mul.f32 	%f157, %f156, %f155;
// 	div.rn.f32 	%f158, %f157, %f187;
// 	st.global.f32 	[%rd32+12], %f158;
// 	add.s32 	%r71, %r71, 4;
// 	add.s64 	%rd33, %rd33, 16;
// 	add.s64 	%rd32, %rd32, 16;
// 	add.s32 	%r70, %r70, -4;
// 	setp.ne.s32 	%p14, %r70, 0;
// 	@%p14 bra 	$L__BB0_18;

// $L__BB0_19:
// 	setp.eq.s32 	%p15, %r72, 0;
// 	@%p15 bra 	$L__BB0_22;

// 	mul.wide.s32 	%rd27, %r71, 4;
// 	add.s64 	%rd35, %rd1, %rd27;
// 	add.s64 	%rd34, %rd2, %rd27;

// $L__BB0_21:
// 	.pragma "nounroll";
// 	ld.global.f32 	%f159, [%rd34];
// 	sub.f32 	%f160, %f159, %f182;
// 	mov.f32 	%f161, 0f3F000000;
// 	mov.f32 	%f162, 0f3BBB989D;
// 	fma.rn.f32 	%f163, %f160, %f162, %f161;
// 	cvt.sat.f32.f32 	%f164, %f163;
// 	mov.f32 	%f165, 0f4B400001;
// 	mov.f32 	%f166, 0f437C0000;
// 	fma.rm.f32 	%f167, %f164, %f166, %f165;
// 	add.f32 	%f168, %f167, 0fCB40007F;
// 	neg.f32 	%f169, %f168;
// 	mov.f32 	%f170, 0f3FB8AA3B;
// 	fma.rn.f32 	%f171, %f160, %f170, %f169;
// 	mov.f32 	%f172, 0f32A57060;
// 	fma.rn.f32 	%f173, %f160, %f172, %f171;
// 	mov.b32 	%r59, %f167;
// 	shl.b32 	%r60, %r59, 23;
// 	mov.b32 	%f174, %r60;
// 	ex2.approx.ftz.f32 	%f175, %f173;
// 	mul.f32 	%f176, %f175, %f174;
// 	div.rn.f32 	%f177, %f176, %f187;
// 	st.global.f32 	[%rd35], %f177;
// 	add.s64 	%rd35, %rd35, 4;
// 	add.s64 	%rd34, %rd34, 4;
// 	add.s32 	%r72, %r72, -1;
// 	setp.ne.s32 	%p16, %r72, 0;
// 	@%p16 bra 	$L__BB0_21;
// 	bra.uni 	$L__BB0_22;

// //