#include <cuda_runtime.h>
#include <math.h>

// Warp-level reduction helpers
__device__ float warpReduceMax(float val) {
    for (int offset = 16; offset > 0; offset /= 2) {
        val = fmaxf(val, __shfl_down_sync(0xffffffff, val, offset));
    }
    return val;
}

__device__ float warpReduceSum(float val) {
    for (int offset = 16; offset > 0; offset /= 2) {
        val += __shfl_down_sync(0xffffffff, val, offset);
    }
    return val;
}

// Pass 1: Find maximum value across input array
__global__ void block_max_kernel(const float* input, float* block_maxes, int N) {
    __shared__ float shared[32];
    int tid = threadIdx.x;
    int idx = blockIdx.x * blockDim.x + threadIdx.x;

    float local_max = -INFINITY;
    for (int i = idx; i < N; i += blockDim.x * gridDim.x) {
        local_max = fmaxf(local_max, input[i]);
    }

    local_max = warpReduceMax(local_max);

    int lane = tid % 32;
    int warp_id = tid / 32;

    if (lane == 0) {
        shared[warp_id] = local_max;
    }
    __syncthreads();

    if (warp_id == 0) {
        float val = (tid < (blockDim.x / 32)) ? shared[lane] : -INFINITY;
        val = warpReduceMax(val);
        if (tid == 0) {
            block_maxes[blockIdx.x] = val;
        }
    }
}

// Pass 2: Compute exponential sum using the max trick
__global__ void block_sum_kernel(const float* input, float* block_sums, float max_val, int N) {
    __shared__ float shared[32];
    int tid = threadIdx.x;
    int idx = blockIdx.x * blockDim.x + threadIdx.x;

    float local_sum = 0.0f;
    for (int i = idx; i < N; i += blockDim.x * gridDim.x) {
        local_sum += expf(input[i] - max_val);
    }

    local_sum = warpReduceSum(local_sum);

    int lane = tid % 32;
    int warp_id = tid / 32;

    if (lane == 0) {
        shared[warp_id] = local_sum;
    }
    __syncthreads();

    if (warp_id == 0) {
        float val = (tid < (blockDim.x / 32)) ? shared[lane] : 0.0f;
        val = warpReduceSum(val);
        if (tid == 0) {
            block_sums[blockIdx.x] = val;
        }
    }
}

// Pass 3: Final Softmax normalization
__global__ void apply_softmax_kernel(const float* input, float* output, float max_val, float sum_val, int N) {
    int idx = blockIdx.x * blockDim.x + threadIdx.x;
    int stride = blockDim.x * gridDim.x;

    for (int i = idx; i < N; i += stride) {
        output[i] = expf(input[i] - max_val) / sum_val;
    }
}

extern "C" void solve(const float* input, float* output, int N) {
    const int threadsPerBlock = 256;
    const int blocks = (N + threadsPerBlock - 1) / threadsPerBlock;
    const int maxBlocks = (blocks > 1024) ? 1024 : blocks;

    float *d_block_maxes, *d_block_sums;
    cudaMalloc(&d_block_maxes, maxBlocks * sizeof(float));
    cudaMalloc(&d_block_sums, maxBlocks * sizeof(float));

    // Step 1: Maximum value reduction
    block_max_kernel<<<maxBlocks, threadsPerBlock>>>(input, d_block_maxes, N);

    float *h_block_maxes = (float*)malloc(maxBlocks * sizeof(float));
    cudaMemcpy(h_block_maxes, d_block_maxes, maxBlocks * sizeof(float), cudaMemcpyDeviceToHost);

    float max_val = -INFINITY;
    for (int i = 0; i < maxBlocks; i++) {
        max_val = fmaxf(max_val, h_block_maxes[i]);
    }

    // Step 2: Sum of exp(x - max) reduction
    block_sum_kernel<<<maxBlocks, threadsPerBlock>>>(input, d_block_sums, max_val, N);

    float *h_block_sums = (float*)malloc(maxBlocks * sizeof(float));
    cudaMemcpy(h_block_sums, d_block_sums, maxBlocks * sizeof(float), cudaMemcpyDeviceToHost);

    float sum_val = 0.0f;
    for (int i = 0; i < maxBlocks; i++) {
        sum_val += h_block_sums[i];
    }

    // Step 3: Compute output
    apply_softmax_kernel<<<maxBlocks, threadsPerBlock>>>(input, output, max_val, sum_val, N);

    cudaFree(d_block_maxes);
    cudaFree(d_block_sums);
    free(h_block_maxes);   
    free(h_block_sums);
}

//Parallel PTX from LeetGPU

// //
// // Generated by NVIDIA NVVM Compiler
// //
// // Compiler Build ID: CL-35404655
// // Cuda compilation tools, release 12.8, V12.8.61
// // Based on NVVM 7.0.1
// //

// .version 8.7
// .target sm_75
// .address_size 64

// 	// .globl	block_max_kernel(float const*, float*, int)
// // block_max_kernel(float const*, float*, int)::shared has been demoted
// // block_sum_kernel(float const*, float*, float, int)::shared has been demoted

// .visible .entry block_max_kernel(float const*, float*, int)(
// 	.param .u64 _Z16block_max_kernelPKfPfi_param_0,
// 	.param .u64 _Z16block_max_kernelPKfPfi_param_1,
// 	.param .u32 _Z16block_max_kernelPKfPfi_param_2
// )
// {
// 	.reg .pred 	%p<17>;
// 	.reg .f32 	%f<33>;
// 	.reg .b32 	%r<62>;
// 	.reg .b64 	%rd<9>;
// 	// demoted variable
// 	.shared .align 4 .b8 block_max_kernel(float const*, float*, int)::shared[128];

// 	ld.param.u64 	%rd2, [_Z16block_max_kernelPKfPfi_param_0];
// 	ld.param.u64 	%rd3, [_Z16block_max_kernelPKfPfi_param_1];
// 	ld.param.u32 	%r9, [_Z16block_max_kernelPKfPfi_param_2];
// 	mov.u32 	%r1, %ntid.x;
// 	mov.u32 	%r2, %ctaid.x;
// 	mov.u32 	%r3, %tid.x;
// 	mad.lo.s32 	%r61, %r2, %r1, %r3;
// 	setp.ge.s32 	%p1, %r61, %r9;
// 	mov.f32 	%f31, 0fFF800000;
// 	@%p1 bra 	$L__BB0_3;

// 	mov.u32 	%r10, %nctaid.x;
// 	mul.lo.s32 	%r5, %r1, %r10;
// 	cvta.to.global.u64 	%rd1, %rd2;
// 	mov.f32 	%f31, 0fFF800000;

// $L__BB0_2:
// 	mul.wide.s32 	%rd4, %r61, 4;
// 	add.s64 	%rd5, %rd1, %rd4;
// 	ld.global.f32 	%f10, [%rd5];
// 	max.f32 	%f31, %f31, %f10;
// 	add.s32 	%r61, %r61, %r5;
// 	setp.lt.s32 	%p2, %r61, %r9;
// 	@%p2 bra 	$L__BB0_2;

// $L__BB0_3:
// 	mov.b32 	%r11, %f31;
// 	mov.u32 	%r12, 2;
// 	mov.u32 	%r13, 31;
// 	mov.u32 	%r14, 16;
// 	mov.u32 	%r15, -1;
// 	shfl.sync.down.b32 	%r16|%p3, %r11, %r14, %r13, %r15;
// 	mov.b32 	%f11, %r16;
// 	max.f32 	%f12, %f31, %f11;
// 	mov.b32 	%r17, %f12;
// 	mov.u32 	%r18, 8;
// 	shfl.sync.down.b32 	%r19|%p4, %r17, %r18, %r13, %r15;
// 	mov.b32 	%f13, %r19;
// 	max.f32 	%f14, %f12, %f13;
// 	mov.b32 	%r20, %f14;
// 	mov.u32 	%r21, 4;
// 	shfl.sync.down.b32 	%r22|%p5, %r20, %r21, %r13, %r15;
// 	mov.b32 	%f15, %r22;
// 	max.f32 	%f16, %f14, %f15;
// 	mov.b32 	%r23, %f16;
// 	shfl.sync.down.b32 	%r24|%p6, %r23, %r12, %r13, %r15;
// 	mov.b32 	%f17, %r24;
// 	max.f32 	%f18, %f16, %f17;
// 	mov.b32 	%r25, %f18;
// 	mov.u32 	%r26, 1;
// 	shfl.sync.down.b32 	%r27|%p7, %r25, %r26, %r13, %r15;
// 	mov.b32 	%f19, %r27;
// 	max.f32 	%f4, %f18, %f19;
// 	shr.s32 	%r28, %r3, 31;
// 	shr.u32 	%r29, %r28, 27;
// 	add.s32 	%r30, %r3, %r29;
// 	and.b32 	%r31, %r30, -32;
// 	sub.s32 	%r8, %r3, %r31;
// 	setp.ne.s32 	%p8, %r8, 0;
// 	@%p8 bra 	$L__BB0_5;

// 	shr.s32 	%r35, %r30, 5;
// 	shl.b32 	%r36, %r35, 2;
// 	mov.u32 	%r37, block_max_kernel(float const*, float*, int)::shared;
// 	add.s32 	%r38, %r37, %r36;
// 	st.shared.f32 	[%r38], %f4;

// $L__BB0_5:
// 	bar.sync 	0;
// 	add.s32 	%r39, %r3, 31;
// 	setp.gt.u32 	%p9, %r39, 62;
// 	@%p9 bra 	$L__BB0_10;

// 	shr.u32 	%r40, %r1, 5;
// 	setp.ge.u32 	%p10, %r3, %r40;
// 	mov.f32 	%f32, 0fFF800000;
// 	@%p10 bra 	$L__BB0_8;

// 	shl.b32 	%r41, %r8, 2;
// 	mov.u32 	%r42, block_max_kernel(float const*, float*, int)::shared;
// 	add.s32 	%r43, %r42, %r41;
// 	ld.shared.f32 	%f32, [%r43];

// $L__BB0_8:
// 	mov.b32 	%r44, %f32;
// 	mov.u32 	%r45, 2;
// 	mov.u32 	%r46, 31;
// 	mov.u32 	%r47, 16;
// 	mov.u32 	%r48, -1;
// 	shfl.sync.down.b32 	%r49|%p11, %r44, %r47, %r46, %r48;
// 	mov.b32 	%f21, %r49;
// 	max.f32 	%f22, %f32, %f21;
// 	mov.b32 	%r50, %f22;
// 	mov.u32 	%r51, 8;
// 	shfl.sync.down.b32 	%r52|%p12, %r50, %r51, %r46, %r48;
// 	mov.b32 	%f23, %r52;
// 	max.f32 	%f24, %f22, %f23;
// 	mov.b32 	%r53, %f24;
// 	mov.u32 	%r54, 4;
// 	shfl.sync.down.b32 	%r55|%p13, %r53, %r54, %r46, %r48;
// 	mov.b32 	%f25, %r55;
// 	max.f32 	%f26, %f24, %f25;
// 	mov.b32 	%r56, %f26;
// 	shfl.sync.down.b32 	%r57|%p14, %r56, %r45, %r46, %r48;
// 	mov.b32 	%f27, %r57;
// 	max.f32 	%f28, %f26, %f27;
// 	mov.b32 	%r58, %f28;
// 	mov.u32 	%r59, 1;
// 	shfl.sync.down.b32 	%r60|%p15, %r58, %r59, %r46, %r48;
// 	mov.b32 	%f29, %r60;
// 	max.f32 	%f7, %f28, %f29;
// 	setp.ne.s32 	%p16, %r3, 0;
// 	@%p16 bra 	$L__BB0_10;

// 	cvta.to.global.u64 	%rd6, %rd3;
// 	mul.wide.u32 	%rd7, %r2, 4;
// 	add.s64 	%rd8, %rd6, %rd7;
// 	st.global.f32 	[%rd8], %f7;

// $L__BB0_10:
// 	ret;

// }
// 	// .globl	block_sum_kernel(float const*, float*, float, int)
// .visible .entry block_sum_kernel(float const*, float*, float, int)(
// 	.param .u64 _Z16block_sum_kernelPKfPffi_param_0,
// 	.param .u64 _Z16block_sum_kernelPKfPffi_param_1,
// 	.param .f32 _Z16block_sum_kernelPKfPffi_param_2,
// 	.param .u32 _Z16block_sum_kernelPKfPffi_param_3
// )
// {
// 	.reg .pred 	%p<17>;
// 	.reg .f32 	%f<50>;
// 	.reg .b32 	%r<64>;
// 	.reg .b64 	%rd<9>;
// 	// demoted variable
// 	.shared .align 4 .b8 block_sum_kernel(float const*, float*, float, int)::shared[128];

// 	ld.param.u64 	%rd2, [_Z16block_sum_kernelPKfPffi_param_0];
// 	ld.param.u64 	%rd3, [_Z16block_sum_kernelPKfPffi_param_1];
// 	ld.param.f32 	%f8, [_Z16block_sum_kernelPKfPffi_param_2];
// 	ld.param.u32 	%r9, [_Z16block_sum_kernelPKfPffi_param_3];
// 	mov.u32 	%r1, %ntid.x;
// 	mov.u32 	%r2, %ctaid.x;
// 	mov.u32 	%r3, %tid.x;
// 	mad.lo.s32 	%r63, %r2, %r1, %r3;
// 	setp.ge.s32 	%p1, %r63, %r9;
// 	mov.f32 	%f48, 0f00000000;
// 	@%p1 bra 	$L__BB1_3;

// 	mov.u32 	%r10, %nctaid.x;
// 	mul.lo.s32 	%r5, %r1, %r10;
// 	cvta.to.global.u64 	%rd1, %rd2;
// 	mov.f32 	%f48, 0f00000000;

// $L__BB1_2:
// 	mul.wide.s32 	%rd4, %r63, 4;
// 	add.s64 	%rd5, %rd1, %rd4;
// 	ld.global.f32 	%f11, [%rd5];
// 	sub.f32 	%f12, %f11, %f8;
// 	mov.f32 	%f13, 0f3F000000;
// 	mov.f32 	%f14, 0f3BBB989D;
// 	fma.rn.f32 	%f15, %f12, %f14, %f13;
// 	cvt.sat.f32.f32 	%f16, %f15;
// 	mov.f32 	%f17, 0f4B400001;
// 	mov.f32 	%f18, 0f437C0000;
// 	fma.rm.f32 	%f19, %f16, %f18, %f17;
// 	add.f32 	%f20, %f19, 0fCB40007F;
// 	neg.f32 	%f21, %f20;
// 	mov.f32 	%f22, 0f3FB8AA3B;
// 	fma.rn.f32 	%f23, %f12, %f22, %f21;
// 	mov.f32 	%f24, 0f32A57060;
// 	fma.rn.f32 	%f25, %f12, %f24, %f23;
// 	mov.b32 	%r11, %f19;
// 	shl.b32 	%r12, %r11, 23;
// 	mov.b32 	%f26, %r12;
// 	ex2.approx.ftz.f32 	%f27, %f25;
// 	fma.rn.f32 	%f48, %f27, %f26, %f48;
// 	add.s32 	%r63, %r63, %r5;
// 	setp.lt.s32 	%p2, %r63, %r9;
// 	@%p2 bra 	$L__BB1_2;

// $L__BB1_3:
// 	mov.b32 	%r13, %f48;
// 	mov.u32 	%r14, 2;
// 	mov.u32 	%r15, 31;
// 	mov.u32 	%r16, 16;
// 	mov.u32 	%r17, -1;
// 	shfl.sync.down.b32 	%r18|%p3, %r13, %r16, %r15, %r17;
// 	mov.b32 	%f28, %r18;
// 	add.f32 	%f29, %f48, %f28;
// 	mov.b32 	%r19, %f29;
// 	mov.u32 	%r20, 8;
// 	shfl.sync.down.b32 	%r21|%p4, %r19, %r20, %r15, %r17;
// 	mov.b32 	%f30, %r21;
// 	add.f32 	%f31, %f29, %f30;
// 	mov.b32 	%r22, %f31;
// 	mov.u32 	%r23, 4;
// 	shfl.sync.down.b32 	%r24|%p5, %r22, %r23, %r15, %r17;
// 	mov.b32 	%f32, %r24;
// 	add.f32 	%f33, %f31, %f32;
// 	mov.b32 	%r25, %f33;
// 	shfl.sync.down.b32 	%r26|%p6, %r25, %r14, %r15, %r17;
// 	mov.b32 	%f34, %r26;
// 	add.f32 	%f35, %f33, %f34;
// 	mov.b32 	%r27, %f35;
// 	mov.u32 	%r28, 1;
// 	shfl.sync.down.b32 	%r29|%p7, %r27, %r28, %r15, %r17;
// 	mov.b32 	%f36, %r29;
// 	add.f32 	%f4, %f35, %f36;
// 	shr.s32 	%r30, %r3, 31;
// 	shr.u32 	%r31, %r30, 27;
// 	add.s32 	%r32, %r3, %r31;
// 	and.b32 	%r33, %r32, -32;
// 	sub.s32 	%r8, %r3, %r33;
// 	setp.ne.s32 	%p8, %r8, 0;
// 	@%p8 bra 	$L__BB1_5;

// 	shr.s32 	%r37, %r32, 5;
// 	shl.b32 	%r38, %r37, 2;
// 	mov.u32 	%r39, block_sum_kernel(float const*, float*, float, int)::shared;
// 	add.s32 	%r40, %r39, %r38;
// 	st.shared.f32 	[%r40], %f4;

// $L__BB1_5:
// 	bar.sync 	0;
// 	add.s32 	%r41, %r3, 31;
// 	setp.gt.u32 	%p9, %r41, 62;
// 	@%p9 bra 	$L__BB1_10;

// 	shr.u32 	%r42, %r1, 5;
// 	setp.ge.u32 	%p10, %r3, %r42;
// 	mov.f32 	%f49, 0f00000000;
// 	@%p10 bra 	$L__BB1_8;

// 	shl.b32 	%r43, %r8, 2;
// 	mov.u32 	%r44, block_sum_kernel(float const*, float*, float, int)::shared;
// 	add.s32 	%r45, %r44, %r43;
// 	ld.shared.f32 	%f49, [%r45];

// $L__BB1_8:
// 	mov.b32 	%r46, %f49;
// 	mov.u32 	%r47, 2;
// 	mov.u32 	%r48, 31;
// 	mov.u32 	%r49, 16;
// 	mov.u32 	%r50, -1;
// 	shfl.sync.down.b32 	%r51|%p11, %r46, %r49, %r48, %r50;
// 	mov.b32 	%f38, %r51;
// 	add.f32 	%f39, %f49, %f38;
// 	mov.b32 	%r52, %f39;
// 	mov.u32 	%r53, 8;
// 	shfl.sync.down.b32 	%r54|%p12, %r52, %r53, %r48, %r50;
// 	mov.b32 	%f40, %r54;
// 	add.f32 	%f41, %f39, %f40;
// 	mov.b32 	%r55, %f41;
// 	mov.u32 	%r56, 4;
// 	shfl.sync.down.b32 	%r57|%p13, %r55, %r56, %r48, %r50;
// 	mov.b32 	%f42, %r57;
// 	add.f32 	%f43, %f41, %f42;
// 	mov.b32 	%r58, %f43;
// 	shfl.sync.down.b32 	%r59|%p14, %r58, %r47, %r48, %r50;
// 	mov.b32 	%f44, %r59;
// 	add.f32 	%f45, %f43, %f44;
// 	mov.b32 	%r60, %f45;
// 	mov.u32 	%r61, 1;
// 	shfl.sync.down.b32 	%r62|%p15, %r60, %r61, %r48, %r50;
// 	mov.b32 	%f46, %r62;
// 	add.f32 	%f7, %f45, %f46;
// 	setp.ne.s32 	%p16, %r3, 0;
// 	@%p16 bra 	$L__BB1_10;

// 	cvta.to.global.u64 	%rd6, %rd3;
// 	mul.wide.u32 	%rd7, %r2, 4;
// 	add.s64 	%rd8, %rd6, %rd7;
// 	st.global.f32 	[%rd8], %f7;

// $L__BB1_10:
// 	ret;

// }
// 	// .globl	apply_softmax_kernel(float const*, float*, float, float, int)
// .visible .entry apply_softmax_kernel(float const*, float*, float, float, int)(
// 	.param .u64 _Z20apply_softmax_kernelPKfPfffi_param_0,
// 	.param .u64 _Z20apply_softmax_kernelPKfPfffi_param_1,
// 	.param .f32 _Z20apply_softmax_kernelPKfPfffi_param_2,
// 	.param .f32 _Z20apply_softmax_kernelPKfPfffi_param_3,
// 	.param .u32 _Z20apply_softmax_kernelPKfPfffi_param_4
// )
// {
// 	.reg .pred 	%p<6>;
// 	.reg .f32 	%f<80>;
// 	.reg .b32 	%r<39>;
// 	.reg .b64 	%rd<25>;


// 	ld.param.u64 	%rd11, [_Z20apply_softmax_kernelPKfPfffi_param_0];
// 	ld.param.u64 	%rd12, [_Z20apply_softmax_kernelPKfPfffi_param_1];
// 	ld.param.f32 	%f1, [_Z20apply_softmax_kernelPKfPfffi_param_2];
// 	ld.param.f32 	%f2, [_Z20apply_softmax_kernelPKfPfffi_param_3];
// 	ld.param.u32 	%r12, [_Z20apply_softmax_kernelPKfPfffi_param_4];
// 	cvta.to.global.u64 	%rd1, %rd12;
// 	cvta.to.global.u64 	%rd2, %rd11;
// 	mov.u32 	%r13, %ntid.x;
// 	mov.u32 	%r14, %ctaid.x;
// 	mov.u32 	%r15, %tid.x;
// 	mad.lo.s32 	%r37, %r14, %r13, %r15;
// 	mov.u32 	%r16, %nctaid.x;
// 	mul.lo.s32 	%r2, %r13, %r16;
// 	setp.ge.s32 	%p1, %r37, %r12;
// 	@%p1 bra 	$L__BB2_7;

// 	add.s32 	%r17, %r2, %r12;
// 	add.s32 	%r18, %r37, %r2;
// 	not.b32 	%r19, %r18;
// 	add.s32 	%r20, %r17, %r19;
// 	div.u32 	%r3, %r20, %r2;
// 	add.s32 	%r21, %r3, 1;
// 	and.b32 	%r36, %r21, 3;
// 	setp.eq.s32 	%p2, %r36, 0;
// 	@%p2 bra 	$L__BB2_4;

// 	mul.wide.s32 	%rd13, %r37, 4;
// 	add.s64 	%rd24, %rd1, %rd13;
// 	mul.wide.s32 	%rd4, %r2, 4;
// 	add.s64 	%rd23, %rd2, %rd13;

// $L__BB2_3:
// 	.pragma "nounroll";
// 	ld.global.f32 	%f3, [%rd23];
// 	sub.f32 	%f4, %f3, %f1;
// 	mov.f32 	%f5, 0f3F000000;
// 	mov.f32 	%f6, 0f3BBB989D;
// 	fma.rn.f32 	%f7, %f4, %f6, %f5;
// 	cvt.sat.f32.f32 	%f8, %f7;
// 	mov.f32 	%f9, 0f4B400001;
// 	mov.f32 	%f10, 0f437C0000;
// 	fma.rm.f32 	%f11, %f8, %f10, %f9;
// 	add.f32 	%f12, %f11, 0fCB40007F;
// 	neg.f32 	%f13, %f12;
// 	mov.f32 	%f14, 0f3FB8AA3B;
// 	fma.rn.f32 	%f15, %f4, %f14, %f13;
// 	mov.f32 	%f16, 0f32A57060;
// 	fma.rn.f32 	%f17, %f4, %f16, %f15;
// 	mov.b32 	%r22, %f11;
// 	shl.b32 	%r23, %r22, 23;
// 	mov.b32 	%f18, %r23;
// 	ex2.approx.ftz.f32 	%f19, %f17;
// 	mul.f32 	%f20, %f19, %f18;
// 	div.rn.f32 	%f21, %f20, %f2;
// 	st.global.f32 	[%rd24], %f21;
// 	add.s32 	%r37, %r37, %r2;
// 	add.s64 	%rd24, %rd24, %rd4;
// 	add.s64 	%rd23, %rd23, %rd4;
// 	add.s32 	%r36, %r36, -1;
// 	setp.ne.s32 	%p3, %r36, 0;
// 	@%p3 bra 	$L__BB2_3;

// $L__BB2_4:
// 	setp.lt.u32 	%p4, %r3, 3;
// 	@%p4 bra 	$L__BB2_7;

// 	mul.wide.s32 	%rd10, %r2, 4;

// $L__BB2_6:
// 	mul.wide.s32 	%rd14, %r37, 4;
// 	add.s64 	%rd15, %rd2, %rd14;
// 	ld.global.f32 	%f22, [%rd15];
// 	sub.f32 	%f23, %f22, %f1;
// 	mov.f32 	%f24, 0f3F000000;
// 	mov.f32 	%f25, 0f3BBB989D;
// 	fma.rn.f32 	%f26, %f23, %f25, %f24;
// 	cvt.sat.f32.f32 	%f27, %f26;
// 	mov.f32 	%f28, 0f4B400001;
// 	mov.f32 	%f29, 0f437C0000;
// 	fma.rm.f32 	%f30, %f27, %f29, %f28;
// 	add.f32 	%f31, %f30, 0fCB40007F;
// 	neg.f32 	%f32, %f31;
// 	mov.f32 	%f33, 0f3FB8AA3B;
// 	fma.rn.f32 	%f34, %f23, %f33, %f32;
// 	mov.f32 	%f35, 0f32A57060;
// 	fma.rn.f32 	%f36, %f23, %f35, %f34;
// 	mov.b32 	%r24, %f30;
// 	shl.b32 	%r25, %r24, 23;
// 	mov.b32 	%f37, %r25;
// 	ex2.approx.ftz.f32 	%f38, %f36;
// 	mul.f32 	%f39, %f38, %f37;
// 	div.rn.f32 	%f40, %f39, %f2;
// 	add.s64 	%rd16, %rd1, %rd14;
// 	st.global.f32 	[%rd16], %f40;
// 	add.s64 	%rd17, %rd15, %rd10;
// 	ld.global.f32 	%f41, [%rd17];
// 	sub.f32 	%f42, %f41, %f1;
// 	fma.rn.f32 	%f43, %f42, %f25, %f24;
// 	cvt.sat.f32.f32 	%f44, %f43;
// 	fma.rm.f32 	%f45, %f44, %f29, %f28;
// 	add.f32 	%f46, %f45, 0fCB40007F;
// 	neg.f32 	%f47, %f46;
// 	fma.rn.f32 	%f48, %f42, %f33, %f47;
// 	fma.rn.f32 	%f49, %f42, %f35, %f48;
// 	mov.b32 	%r26, %f45;
// 	shl.b32 	%r27, %r26, 23;
// 	mov.b32 	%f50, %r27;
// 	ex2.approx.ftz.f32 	%f51, %f49;
// 	mul.f32 	%f52, %f51, %f50;
// 	div.rn.f32 	%f53, %f52, %f2;
// 	add.s64 	%rd18, %rd16, %rd10;
// 	st.global.f32 	[%rd18], %f53;
// 	add.s32 	%r28, %r37, %r2;
// 	add.s32 	%r29, %r28, %r2;
// 	add.s64 	%rd19, %rd17, %rd10;
// 	ld.global.f32 	%f54, [%rd19];
// 	sub.f32 	%f55, %f54, %f1;
// 	fma.rn.f32 	%f56, %f55, %f25, %f24;
// 	cvt.sat.f32.f32 	%f57, %f56;
// 	fma.rm.f32 	%f58, %f57, %f29, %f28;
// 	add.f32 	%f59, %f58, 0fCB40007F;
// 	neg.f32 	%f60, %f59;
// 	fma.rn.f32 	%f61, %f55, %f33, %f60;
// 	fma.rn.f32 	%f62, %f55, %f35, %f61;
// 	mov.b32 	%r30, %f58;
// 	shl.b32 	%r31, %r30, 23;
// 	mov.b32 	%f63, %r31;
// 	ex2.approx.ftz.f32 	%f64, %f62;
// 	mul.f32 	%f65, %f64, %f63;
// 	div.rn.f32 	%f66, %f65, %f2;
// 	add.s64 	%rd20, %rd18, %rd10;
// 	st.global.f32 	[%rd20], %f66;
// 	add.s32 	%r32, %r29, %r2;
// 	add.s64 	%rd21, %rd19, %rd10;
// 	ld.global.f32 	%f67, [%rd21];
// 	sub.f32 	%f68, %f67, %f1;
// 	fma.rn.f32 	%f69, %f68, %f25, %f24;
// 	cvt.sat.f32.f32 	%f70, %f69;
// 	fma.rm.f32 	%f71, %f70, %f29, %f28;
// 	add.f32 	%f72, %f71, 0fCB40007F;
// 	neg.f32 	%f73, %f72;
// 	fma.rn.f32 	%f74, %f68, %f33, %f73;
// 	fma.rn.f32 	%f75, %f68, %f35, %f74;
// 	mov.b32 	%r33, %f71;
// 	shl.b32 	%r34, %r33, 23;
// 	mov.b32 	%f76, %r34;
// 	ex2.approx.ftz.f32 	%f77, %f75;
// 	mul.f32 	%f78, %f77, %f76;
// 	div.rn.f32 	%f79, %f78, %f2;
// 	add.s64 	%rd22, %rd20, %rd10;
// 	st.global.f32 	[%rd22], %f79;
// 	add.s32 	%r37, %r32, %r2;
// 	setp.lt.s32 	%p5, %r37, %r12;
// 	@%p5 bra 	$L__BB2_6;

// $L__BB2_7:
// 	ret;

// }