#include <cuda_runtime.h>

__global__ void leaky_relu_kernel(const float* input, float* output, float alpha, int N) {
    int idx = blockIdx.x * blockDim.x + threadIdx.x;
    if (idx < N) {
        float val = input[idx];
        output[idx] = (val > 0.0f) ? val : (val * alpha);
    }
    
}

extern "C" void solve(const float* input, float* output, float alpha, int N) {
    int threads = 256;
    int blocks = (N + threads - 1) / threads;
    leaky_relu_kernel<<<blocks, threads>>>(input, output, alpha, N);
    cudaDeviceSynchronize();
}

//PTX from LeetGPU
// //
// // Generated by NVIDIA NVVM Compiler
// //
// // Compiler Build ID: CL-35404655
// // Cuda compilation tools, release 12.8, V12.8.61
// // Based on NVVM 7.0.1
// //

// .version 8.7
// .target sm_75
// .address_size 64

// 	// .globl	leaky_relu_kernel(float const*, float*, float, int)

// .visible .entry leaky_relu_kernel(float const*, float*, float, int)(
// 	.param .u64 _Z17leaky_relu_kernelPKfPffi_param_0,
// 	.param .u64 _Z17leaky_relu_kernelPKfPffi_param_1,
// 	.param .f32 _Z17leaky_relu_kernelPKfPffi_param_2,
// 	.param .u32 _Z17leaky_relu_kernelPKfPffi_param_3
// )
// {
// 	.reg .pred 	%p<3>;
// 	.reg .f32 	%f<5>;
// 	.reg .b32 	%r<6>;
// 	.reg .b64 	%rd<8>;


// 	ld.param.u64 	%rd1, [_Z17leaky_relu_kernelPKfPffi_param_0];
// 	ld.param.u64 	%rd2, [_Z17leaky_relu_kernelPKfPffi_param_1];
// 	ld.param.f32 	%f1, [_Z17leaky_relu_kernelPKfPffi_param_2];
// 	ld.param.u32 	%r2, [_Z17leaky_relu_kernelPKfPffi_param_3];
// 	mov.u32 	%r3, %ctaid.x;
// 	mov.u32 	%r4, %ntid.x;
// 	mov.u32 	%r5, %tid.x;
// 	mad.lo.s32 	%r1, %r3, %r4, %r5;
// 	setp.ge.s32 	%p1, %r1, %r2;
// 	@%p1 bra 	$L__BB0_2;

// 	cvta.to.global.u64 	%rd3, %rd1;
// 	mul.wide.s32 	%rd4, %r1, 4;
// 	add.s64 	%rd5, %rd3, %rd4;
// 	ld.global.f32 	%f2, [%rd5];
// 	setp.gt.f32 	%p2, %f2, 0f00000000;
// 	mul.f32 	%f3, %f2, %f1;
// 	selp.f32 	%f4, %f2, %f3, %p2;
// 	cvta.to.global.u64 	%rd6, %rd2;
// 	add.s64 	%rd7, %rd6, %rd4;
// 	st.global.f32 	[%rd7], %f4;

// $L__BB0_2:
// 	ret;

// }